powershell-yaml.psm1
We are not able to serialize the array `$a = @($false)` or variable `$a = $false` because function returns early.
Array case:
```
PS C:\Users\ibalutoiu> $a = @($false)
PS C:\Users\ibalutoiu> $a.Count
1
PS C:\Users\ibalutoiu> !$a
True
```
=> Fixed 'ConvertTo-Yaml'

Tests/powershell-yaml.Tests.ps1, powershell-yaml.psm1
Thanks for providing this great module. We need a way to store integer values with leading zeroes and so far all zeroes are removed by how Convert-ValueToProperType tries to cast values. I would like to propose only trying the cast if the node style is 'Plain'.
After the change the following block
```
T1: "001"
T2: '001'
T3: 001
```
results in
```
Name                           Value                                                                                        
----                           -----                                                                                        
T1                             001                                                                                          
T2                             001 …
```
=> Support for int value as string

powershell-yaml.psm1
We need to change yaml files that do not contain any type information. When converting the data back to yaml, it looks like this:
``` PowerShell
$h = @{
k1 = 'v1'
k2 = 'v2'
}
$h | ConvertTo-Yaml
```
```
!System.Collections.Hashtable,%20mscorlib,%20Version=4.0.0.0,%20Culture=neutral,%20PublicKeyToken=b77a5c561934e089
k1: v1
k2: v2
```
The change makes the serialization options accessible. Still the default is RoundTrip but the caller can choose directly, for example EmitDefaults or JsonCompatible. There is no need anymore to have a switch that just allows for JsonCompatible.
``` PowerShell
$h = @{
k1 = 'v1'
k2 = 'v2'
}
$h | ConvertTo-Yaml -Options EmitDefaults
```
```
k1: v1
k2: v2
```
=> ConvertTo-Yaml without tags

powershell-yaml.psm1
Hi,
I noticed the `-ordered` parameter at the moment does not support hashtables nested inside arrays. This PR should be fixing that by passing the parameter through the array processing function.
=> Support nested ordered structures

Tests/powershell-yaml.Tests.ps1
All the tests that used Compare-Equal now use Assert-Equivalent the more strict mode that compares equality (and not equivalency). All assertions use the non-legacy syntax with dashes (-).
Fixes #43
=> Use Assert instead of custom comparison function

powershell-yaml.psm1
Some applications require the leading '-' even if there is only a single element. Added the KeepArray switch to give the option of not stripping the array to a single element.
=> Added KeepArray switch to ConvertTo-Yaml

Load-Assemblies.ps1
Detect `YamlDotNet` availability by checking if type can be resolved instead
`[System.AppDomain]::CurrentDomain.GetAssemblies()` returns all loaded assemblies in .NET, regardless of which `AssemblyLoadContext` they are from. However, in PowerShell, assemblies loaded in a custom `AssemblyLoadContext` are not considered discoverable -- they are supposed to be isolated from the default `AssemblyLoadContext` and resolving types from them could cause the conflicting type identity issue (the type "a.b" cannot be cast to "a.b", becasue they are from different assemblies that are loaded in different assembly load contexts).
Therefore, `[System.AppDomain]::CurrentDomain.GetAssemblies() | ? Location -Match "YamlDotNet.dll"` may return you a `YamlDotNet` assembly that was loaded into a custom …
=> Detect `YamlDotNet` availability by checking if type can be resolved instead

Load-Assemblies.ps1
Problem occured on a Windows Server 2016 host where the powershell 4.0 installation does not provide a "PSEdition" key in $PSVersionTable. If PSEdition is not set, this PR will load the net35 assembly as a default.
=> Prevent error on missing PSEdition key in PSVersionTable

powershell-yaml.psm1
Explicitly export desired function names and aliases without using *.
Fixes: #98
=> Export functions and aliases

powershell-yaml.psm1
Check if the ```StringQuotingEmitter``` already exists in the current namespace. Only attempt to add it if it does not.
Fixes: #68
=> Check if StringQuotingEmitter is already added

powershell-yaml.psm1
Strings that are tagged with ```!!timestamp``` will be converted to UTC time instead of local time. This change also uses ```RoundTripKind``` date time style.
Fixes: #69
=> Default date conversions to UTC and RoundTripKind

powershell-yaml.psm1
This change fixes a conflict between a hashtable key called "Keys" and the "Keys" property that exists as part of an IDictionary. This same fix will avoid any conflicts with other properties.
Fixes: https://github.com/cloudbase/powershell-yaml/issues/111
Thanks @SGStino!
=> Fix conflict in hashtable

.github/workflows/ci.yaml, Tests/powershell-yaml.Tests.ps1
This change pins the Assert powershell module to version 0.9.6.
=> Pin Assert to 0.9.6

Tests/powershell-yaml.Tests.ps1, powershell-yaml.psm1
Powershell is case aware but case insensitive for keys. By default if we create a hashtable @{}, keys are case insensitive. To force case sensitivity in hashtables, we need to call the C# constructor.
=> Fix losing case sensitive keys

powershell-yaml.psd1
- Add some links in `powershell-yaml.psd1` to associate the github repository with the Powershell Gallery.
- When users visit the Powershell Gallery, it's easier to find the Github repository .
=> Add some links in `powershell-yaml.psd1` to associate the repository with the Powershell Gallery.

Tests/powershell-yaml.Tests.ps1, powershell-yaml.psm1
Using [Globalization.NumberStyles]::Any when parsing numbers will parse even numbers that should be returned as strings, such as "2018+".
Explicitly using Integer and/or Float, will correclty parse integers and scientific notation integers such as 1e+3.
Fixes: #145
=> Switch from "Any" number style when parsing number

powershell-yaml.psd1
=> Release version 0.4.9

Tests/powershell-yaml.Tests.ps1, powershell-yaml.psm1
PowerShell considers the integer 0 as a false value when used in an if statement. We need to explicitly compare the result to `$null`.
Fixes: #164
=> Fix broken if comparison

Tests/powershell-yaml.Tests.ps1, powershell-yaml.psm1
Decimals offer much greater precission as opposed to double at the cost of performance. However, in most cases, precission is desirable.
Thanks @amis92 !
Fixes: #152
=> Use decimal as first option when parsing floats

Tests/powershell-yaml.Tests.ps1
This change adds a few more test cases.
=> Add aditional tests

Tests/powershell-yaml.Tests.ps1, powershell-yaml.psm1
This change switches from double to decimal for yaml scalars with the !!float tag. This change also adds aditional test cases.
=> Use decimals instead of double for tagged floats

powershell-yaml.psd1
This change bumps the version and adds release notes in preparation for the release of v0.4.11.
=> Bump version and add release notes

powershell-yaml.psm1
This change makes the assembly resolve handler be more strict when checking whether or not to load the YamlDotNet assembly.
This should prevent accidentally loading the YamlDotNet assembly as a result of a request coming from another assembly that is looking to load a different assembly.
=> Fix potential erroneous load of assembly

Tests/powershell-yaml.Tests.ps1
Add a new test case that checks if we can serialize deeply nested objects.
=> Add new test for depth
